apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  namespace: devops-tools
  labels:
    app: sonar
spec:
  selector:
    app: sonar
  type: NodePort  
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30082
    name: sonar
    